version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
  titan-chest-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: titan-chest-ui
    volumes:
      - .:/app

networks:
  default:
    external:
      name: titan-chest-network
