export const projectForm = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    value: '',
  },
  {
    name: 'address',
    label: 'Address',
    type: 'text',
    value: '',
  },
  {
    name: 'treasury_address',
    label: 'Treasury address',
    type: 'text',
    value: '',
  },
  {
    name: 'rfv_address',
    label: 'RFV address',
    type: 'text',
    value: '',
  },
  {
    name: 'holders_endpoint',
    label: 'Holders endpoint',
    type: 'text',
    value: '',
  },
  {
    name: 'average_holdings_endpoint',
    label: 'Average holdings endpoint',
    type: 'text',
    value: '',
  },
  {
    name: 'abi_id',
    label: 'ABI',
    type: 'select',
    value: 0,
    data: [],
  },
  {
    name: 'network_id',
    label: 'Network',
    type: 'select',
    value: 0,
    data: [],
  },
  {
    name: 'token_id',
    label: 'LP Pair Token',
    type: 'select',
    value: 0,
    data: [],
  },
  {
    name: 'token_pair_id',
    label: 'LP Pair Token\'s Pair',
    type: 'select',
    value: 0,
    data: [],
  },
  {
    name: 'enabled',
    label: 'Enabled',
    type: 'checkbox',
    value: false,
  },
];
